(ns pgloader.source.pgsql
  (:require [pgloader.source.protocol :refer [Source partition-source]]
            [hugsql.core :as hugsql]
            [clojure.string :as str]
            [next.jdbc :as jdbc]
            [clojure.tools.logging :as log])
  (:import [java.sql Connection DriverManager ResultSet]))

(set! *warn-on-reflection* true)

(hugsql/def-db-fns "pgloader/source/pgsql.sql")
(hugsql/def-sqlvec-fns "pgloader/source/pgsql.sql")

(defn- connection
  [uri-map]
  (let [host (or (:host uri-map) "localhost")
        port (or (:port uri-map) 5432)
        db   (or (:db uri-map) "")
        url  (or (:jdbc-url uri-map)
                 (str "jdbc:postgresql://" host ":" port "/" db))
        props (java.util.Properties.)]
    (when (:user uri-map) (.setProperty props "user" (:user uri-map)))
    (when (:password uri-map) (.setProperty props "password" (:password uri-map)))
    (.setProperty props "ApplicationName" "pgloader-source")
    (DriverManager/getConnection url props)))

(def ^:private pg-type-map
  {"smallint" "smallint"
   "integer" "integer"
   "bigint" "bigint"
   "real" "double precision"
   "double precision" "double precision"
   "numeric" "numeric"
   "boolean" "boolean"
   "text" "text"
   "character varying" "text"
   "character" "text"
   "name" "text"
   "bytea" "bytea"
   "timestamp without time zone" "timestamp"
   "timestamp with time zone" "timestamptz"
   "date" "date"
   "time without time zone" "time"
   "time with time zone" "timetz"
   "interval" "interval"
   "json" "json"
   "jsonb" "jsonb"
   "uuid" "uuid"
   "inet" "inet"
   "point" "point"
   "line" "line"
   "lseg" "lseg"
   "box" "box"
   "path" "path"
   "polygon" "polygon"
   "circle" "circle"
   "bit" "bit"
   "bit varying" "varbit"
   "macaddr" "macaddr"
   "macaddr8" "macaddr8"
   "cidr" "cidr"
   "money" "money"
   "tsvector" "tsvector"
   "tsquery" "tsquery"
   "int4range" "int4range"
   "int8range" "int8range"
   "numrange" "numrange"
   "tsrange" "tsrange"
   "tstzrange" "tstzrange"
   "daterange" "daterange"})

(defn- pg-type->pg [type-name]
  (let [lower (str/lower-case type-name)]
    (get pg-type-map lower "text")))

(def ^:private udt-type-map
  {"text"        "text"    "varchar"     "text"    "bpchar"      "text"
   "int2"        "smallint" "int4"       "integer" "int8"        "bigint"
   "float4"      "real"    "float8"      "double precision"
   "numeric"     "numeric" "bool"        "boolean"
   "date"        "date"    "timestamp"   "timestamp without time zone"
   "timestamptz" "timestamptz" "time"    "time"    "timetz"      "timetz"
   "interval"    "interval"
   "json"        "json"    "jsonb"       "jsonb"   "uuid"        "uuid"
   "inet"        "inet"    "cidr"        "cidr"    "macaddr"     "macaddr"
   "point"       "point"   "bytea"       "bytea"   "money"       "money"})

(defn- pg-array-type->pg
  "Resolve an ARRAY column type from udt_name (e.g. '_text' → 'text[]')."
  [udt-name]
  (when (and udt-name (str/starts-with? udt-name "_"))
    (let [elem (subs udt-name 1)]
      (str (get udt-type-map elem elem) "[]"))))

(defn- detect-autoincrement
  "Detect if a column is auto-increment (serial/bigserial/identity)
   by checking the column_default for nextval() or identity patterns."
  [column-default column-name data-type]
  (when column-default
    (let [upper (str/upper-case column-default)]
      (or (str/includes? upper "NEXTVAL(")
          (str/includes? upper "GENERATED BY DEFAULT AS IDENTITY")
          (str/includes? upper "GENERATED ALWAYS AS IDENTITY")))))

(defn- parse-fk-rules
  [fks]
  (let [grouped (group-by :constraint_name fks)]
    (mapv (fn [[cname rows]]
            {:name cname
             :columns (mapv :column_name rows)
             :ftable (-> rows first :foreign_table_name)
             :fcols (mapv :foreign_column_name rows)
             :on-delete (-> rows first :delete_rule)
             :on-update (-> rows first :update_rule)})
          grouped)))

(defn- build-index-cols [^java.sql.Connection conn index-name]
  (try
    (mapv :column_name (table-index-cols conn {:index_name index-name}))
    (catch Exception _
      [])))

(declare pgsql-partition-source)

(defn- split-range-pg
  "Divide [lo, hi) into chunks of size chunk-size. Returns seq of [lo hi] pairs."
  [lo hi chunk-size]
  (when (and lo hi (< lo hi) (pos? chunk-size))
    (take-while (fn [[a _]] (< a hi))
                (iterate (fn [[_ b]] [b (min hi (+ b chunk-size))])
                         [lo (min hi (+ lo chunk-size))]))))

(defn- distribute-pg
  "Round-robin distribute coll across n buckets. Returns vector of n vectors."
  [coll n]
  (let [buckets (mapv (fn [_] (transient [])) (range n))]
    (doseq [[i item] (map-indexed vector coll)]
      (conj! (nth buckets (mod i n)) item))
    (mapv persistent! buckets)))

(deftype PGSQLSource
         [^Connection conn
          ^String source-name-str
          uri-map   ; connection parameters, used by partition-source to clone connections
          ctid-lo   ; Long block number (inclusive) for ctid range scan, or nil
          ctid-hi]  ; Long block number (exclusive) for ctid range scan, or nil

  Source
  (source-name [_] source-name-str)

  (catalog [_]
    (log/info "Fetching table list from PostgreSQL")
    (let [ts (try
               (tables conn)
               (catch Exception e
                 (log/error (str "Failed to list tables: " (.getMessage e)))
                 []))]
      (log/debug (str "Fetched schema for " (count ts) " tables"))
      (->> ts
           (mapv (fn [t]
                   (let [schema (:table_schema t)
                         table-name (:table_name t)
                         cols (columns conn {:schema schema :table table-name})
                         pkeys (table-pkeys conn {:schema schema :table table-name})
                         idxes (table-indexes conn {:schema schema :table table-name})
                         fks   (table-fkeys conn {:schema schema :table table-name})]
                     {:table-name table-name
                      :schema schema
                      :source-schema schema
                      :columns (mapv (fn [c]
                                       (let [col-type (:data_type c)
                                             is-pk (some #(= (:column_name c) %) (mapv :column_name pkeys))
                                             ai (detect-autoincrement (:column_default c) (:column_name c) col-type)]
                                         {:column-name (:column_name c)
                                          :source-column-type col-type
                                          :column-type (cond
                                                         (and ai is-pk) "bigserial"
                                                         (= col-type "ARRAY")
                                                         (or (pg-array-type->pg (:udt_name c)) "text[]")
                                                         ;; Preserve precision for temporal types
                                                         (and (re-find #"(?i)^(timestamp|time)\b" (pg-type->pg col-type))
                                                              (:datetime_precision c))
                                                         (str (pg-type->pg col-type) "(" (:datetime_precision c) ")")
                                                         :else (pg-type->pg col-type))
                                          :is-nullable (= "YES" (:is_nullable c))
                                          :column-default (when-not ai (:column_default c))
                                          :extra (when ai "auto_increment")}))
                                     cols)
                      :primary-key (mapv :column_name pkeys)
                      :indexes (->> idxes
                                    (mapv (fn [idx]
                                            {:name (:index_name idx)
                                             :unique (str/includes? (str/upper-case (:index_def idx)) "UNIQUE")
                                             :columns (build-index-cols conn (:index_name idx))}))
                                    (filterv #(seq (:columns %))))
                      :fkeys (parse-fk-rules fks)})))
           (sort-by :table-name))))

  (read-rows [_ table-spec-entry]
    (let [{:keys [table-name columns schema citus-read-sql]} table-spec-entry
          source-schema (or (:source-schema table-spec-entry) schema)
          base-sql (or citus-read-sql
                       (let [col-names (mapv :column-name columns)
                             col-list (str/join ", " (map #(str "\"" % "\"") col-names))]
                         (str "SELECT " col-list " FROM \"" source-schema "\".\"" table-name "\"")))
          sql (if (and ctid-lo ctid-hi)
                (str base-sql " " (first (ctid-where-sqlvec {:lo (str "'(" ctid-lo ",0)'::tid")
                                                             :hi (str "'(" ctid-hi ",0)'::tid")})))
                base-sql)
          _ (log/debug (str "PGSQL read-rows: " sql))
          stmt (.prepareStatement conn sql)]
      (try
        (.setFetchSize stmt 1000)
        (.setFetchDirection stmt ResultSet/FETCH_FORWARD)
        (let [rs (.executeQuery stmt)
              meta (.getMetaData rs)
              n (.getColumnCount meta)]
          ((fn thisfn []
             (when (.next rs)
               (lazy-seq
                (cons (loop [i 1
                             result (transient [])]
                        (if (<= i n)
                          (recur (inc i)
                                 (conj! result
                                        (let [v (.getObject rs i)]
                                          (when v (str v)))))
                          (persistent! result)))
                      (thisfn)))))))
        (catch Exception e
          (log/error (str "Query failed: " sql " - " (.getMessage e)))
          (throw e)))))

  (read-query [_ sql]
    (let [stmt (.prepareStatement conn sql)]
      (try
        (.setFetchSize stmt 1000)
        (.setFetchDirection stmt ResultSet/FETCH_FORWARD)
        (let [rs (.executeQuery stmt)
              meta (.getMetaData rs)
              n (.getColumnCount meta)
              cols (vec (map (fn [i]
                               {:column-name (.getColumnName meta i)
                                :column-type (.getColumnTypeName meta i)})
                             (range 1 (inc n))))]
          {:columns cols
           :rows
           ((fn thisfn []
              (when (.next rs)
                (lazy-seq
                 (cons (loop [i 1 result (transient [])]
                         (if (<= i n)
                           (recur (inc i)
                                  (conj! result
                                         (let [v (.getObject rs i)]
                                           (when v (str v)))))
                           (persistent! result)))
                       (thisfn))))))})
        (catch Exception e
          (log/error (str "Query failed: " sql " - " (.getMessage e)))
          (throw e)))))

  (partition-source [this table-spec-entry n chunk-bytes]
    (pgsql-partition-source this table-spec-entry n chunk-bytes))

  (close! [this]
    (try (.close conn) (catch Exception _))))

(defn create-source
  [uri-map _table-spec]
  (let [conn (connection uri-map)]
    (->PGSQLSource conn (:raw uri-map) uri-map nil nil)))

(defn pgsql-partition-source
  [^PGSQLSource src table-spec-entry n chunk-bytes]
  (let [conn           (.-conn src)
        source-name-str (.-source_name_str src)
        uri-map        (.-uri_map src)]
    (when (and uri-map (pos? n) (pos? chunk-bytes))
      (let [schema     (or (:source-schema table-spec-entry) (:schema table-spec-entry))
            table-name (:table-name table-spec-entry)]
        (try
          (let [ver-num  (:version_num (server-version-num conn))
                _        (when (< ver-num 140000)
                           (log/debug (str "PG " (quot ver-num 10000) " < 14; skipping ctid partition for " table-name))
                           (throw (ex-info "PG < 14" {:skip true})))
                relpages (some-> (table-relpages conn {:schema schema :table table-name}) :relpages long)]
            (when (and relpages (> relpages 0))
              (let [pages-per-chunk (max 10 (long (/ chunk-bytes 8192)))
                    ranges          (vec (split-range-pg 0 relpages pages-per-chunk))]
                (when (>= (count ranges) 2)
                  (let [buckets (distribute-pg ranges n)]
                    (keep-indexed
                     (fn [_i bucket]
                       (when (seq bucket)
                         (let [lo (ffirst bucket)
                               hi (second (last bucket))]
                           (->PGSQLSource (connection uri-map) source-name-str uri-map lo hi))))
                     buckets))))))
          (catch clojure.lang.ExceptionInfo e
            (when-not (:skip (ex-data e)) (log/warn (str "partition-source PG: " (.getMessage e))))
            nil)
          (catch Exception e
            (log/warn (str "partition-source PG: could not partition " table-name ": " (.getMessage e)))
            nil))))))
