(ns pgloader.source.pgsql
  (:require [pgloader.source.protocol :refer [Source]]
            [hugsql.core :as hugsql]
            [clojure.string :as str]
            [next.jdbc :as jdbc]
            [clojure.tools.logging :as log])
  (:import [java.sql Connection DriverManager ResultSet]))

(set! *warn-on-reflection* true)

(hugsql/def-db-fns "pgloader/source/pgsql.sql")

(defn- connection
  [uri-map]
  (let [host (or (:host uri-map) "localhost")
        port (or (:port uri-map) 5432)
        db   (or (:db uri-map) "")
        url  (str "jdbc:postgresql://" host ":" port "/" db)
        props (java.util.Properties.)]
    (when (:user uri-map) (.setProperty props "user" (:user uri-map)))
    (when (:password uri-map) (.setProperty props "password" (:password uri-map)))
    (.setProperty props "ApplicationName" "pgloader-source")
    (DriverManager/getConnection url props)))

(def ^:private pg-type-map
  {"smallint" "smallint"
   "integer" "bigint"
   "bigint" "bigint"
   "real" "double precision"
   "double precision" "double precision"
   "numeric" "numeric"
   "boolean" "boolean"
   "text" "text"
   "character varying" "text"
   "character" "text"
   "name" "text"
   "bytea" "bytea"
   "timestamp without time zone" "timestamptz"
   "timestamp with time zone" "timestamptz"
   "date" "date"
   "time without time zone" "time"
   "time with time zone" "timetz"
   "interval" "interval"
   "json" "json"
   "jsonb" "jsonb"
   "uuid" "uuid"
   "inet" "inet"
   "point" "point"
   "line" "line"
   "lseg" "lseg"
   "box" "box"
   "path" "path"
   "polygon" "polygon"
   "circle" "circle"
   "bit" "bit"
   "bit varying" "varbit"
   "macaddr" "macaddr"
   "macaddr8" "macaddr8"
   "cidr" "cidr"
   "money" "money"
   "tsvector" "tsvector"
   "tsquery" "tsquery"
   "int4range" "int4range"
   "int8range" "int8range"
   "numrange" "numrange"
   "tsrange" "tsrange"
   "tstzrange" "tstzrange"
   "daterange" "daterange"})

(defn- pg-type->pg [type-name]
  (let [lower (str/lower-case type-name)]
    (get pg-type-map lower "text")))

(def ^:private udt-type-map
  {"text"        "text"    "varchar"     "text"    "bpchar"      "text"
   "int2"        "smallint" "int4"       "integer" "int8"        "bigint"
   "float4"      "real"    "float8"      "double precision"
   "numeric"     "numeric" "bool"        "boolean"
   "date"        "date"    "timestamp"   "timestamp without time zone"
   "timestamptz" "timestamptz" "time"    "time"    "timetz"      "timetz"
   "interval"    "interval"
   "json"        "json"    "jsonb"       "jsonb"   "uuid"        "uuid"
   "inet"        "inet"    "cidr"        "cidr"    "macaddr"     "macaddr"
   "point"       "point"   "bytea"       "bytea"   "money"       "money"})

(defn- pg-array-type->pg
  "Resolve an ARRAY column type from udt_name (e.g. '_text' → 'text[]')."
  [udt-name]
  (when (and udt-name (str/starts-with? udt-name "_"))
    (let [elem (subs udt-name 1)]
      (str (get udt-type-map elem elem) "[]"))))

(defn- detect-autoincrement
  "Detect if a column is auto-increment (serial/bigserial/identity)
   by checking the column_default for nextval() or identity patterns."
  [column-default column-name data-type]
  (when column-default
    (let [upper (str/upper-case column-default)]
      (or (str/includes? upper "NEXTVAL(")
          (str/includes? upper "GENERATED BY DEFAULT AS IDENTITY")
          (str/includes? upper "GENERATED ALWAYS AS IDENTITY")))))

(defn- parse-fk-rules
  [fks]
  (let [grouped (group-by :constraint_name fks)]
    (mapv (fn [[cname rows]]
            {:name cname
             :columns (mapv :column_name rows)
             :ftable (-> rows first :foreign_table_name)
             :fcols (mapv :foreign_column_name rows)
             :on-delete (-> rows first :delete_rule)
             :on-update (-> rows first :update_rule)})
          grouped)))

(defn- build-index-cols [^java.sql.Connection conn index-name]
  (try
    (mapv :column_name (table-index-cols conn {:index_name index-name}))
    (catch Exception _
      [])))

(deftype PGSQLSource
  [^Connection conn
   ^String source-name-str]

  Source
  (source-name [_] source-name-str)

  (catalog [_]
    (log/info "Fetching table list from PostgreSQL")
    (let [ts (try
               (tables conn)
               (catch Exception e
                 (log/error (str "Failed to list tables: " (.getMessage e)))
                 []))]
      (log/debug (str "Fetched schema for " (count ts) " tables"))
      (->> ts
           (mapv (fn [t]
                   (let [schema (:table_schema t)
                         table-name (:table_name t)
                         cols (columns conn {:schema schema :table table-name})
                         pkeys (table-pkeys conn {:schema schema :table table-name})
                         idxes (table-indexes conn {:schema schema :table table-name})
                         fks   (table-fkeys conn {:schema schema :table table-name})]
                      {:table-name table-name
                       :schema schema
                       :source-schema schema
                       :columns (mapv (fn [c]
                                       (let [col-type (:data_type c)
                                             is-pk (some #(= (:column_name c) %) (mapv :column_name pkeys))
                                             ai (detect-autoincrement (:column_default c) (:column_name c) col-type)]
                                         {:column-name (:column_name c)
                                          :column-type (if (and ai is-pk)
                                                         "bigserial"
                                                         (if (= col-type "ARRAY")
                                                           (or (pg-array-type->pg (:udt_name c)) "text[]")
                                                           (pg-type->pg col-type)))
                                          :is-nullable (= "YES" (:is_nullable c))
                                           :column-default (when-not ai (:column_default c))
                                          :extra (when ai "auto_increment")}))
                                     cols)
                      :primary-key (mapv :column_name pkeys)
                      :indexes (->> idxes
                                   (mapv (fn [idx]
                                           {:name (:index_name idx)
                                            :unique (str/includes? (str/upper-case (:index_def idx)) "UNIQUE")
                                            :columns (build-index-cols conn (:index_name idx))}))
                                   (filterv #(seq (:columns %))))
                      :fkeys (parse-fk-rules fks)})))
           (sort-by :table-name))))

  (read-rows [_ table-spec-entry]
    (let [{:keys [table-name columns schema citus-read-sql]} table-spec-entry
          source-schema (or (:source-schema table-spec-entry) schema)
          sql (or citus-read-sql
                  (let [col-names (mapv :column-name columns)
                        col-list (str/join ", " (map #(str "\"" % "\"") col-names))]
                    (str "SELECT " col-list " FROM \"" source-schema "\".\"" table-name "\"")))
          _ (log/debug (str "PGSQL read-rows: " sql))
          stmt (.prepareStatement conn sql)]
      (try
        (.setFetchSize stmt 1000)
        (.setFetchDirection stmt ResultSet/FETCH_FORWARD)
        (let [rs (.executeQuery stmt)
              meta (.getMetaData rs)
              n (.getColumnCount meta)]
          ((fn thisfn []
             (when (.next rs)
               (lazy-seq
                 (cons (loop [i 1
                              result (transient [])]
                         (if (<= i n)
                           (recur (inc i)
                                  (conj! result
                                    (let [v (.getObject rs i)]
                                      (when v (str v)))))
                           (persistent! result)))
                       (thisfn)))))))
        (catch Exception e
          (log/error (str "Query failed: " sql " - " (.getMessage e)))
          (throw e)))))

  (read-query [_ sql]
    (let [stmt (.prepareStatement conn sql)]
      (try
        (.setFetchSize stmt 1000)
        (.setFetchDirection stmt ResultSet/FETCH_FORWARD)
        (let [rs (.executeQuery stmt)
              meta (.getMetaData rs)
              n (.getColumnCount meta)
              cols (vec (map (fn [i]
                               {:column-name (.getColumnName meta i)
                                :column-type (.getColumnTypeName meta i)})
                             (range 1 (inc n))))]
          {:columns cols
           :rows
           ((fn thisfn []
              (when (.next rs)
                (lazy-seq
                  (cons (loop [i 1 result (transient [])]
                          (if (<= i n)
                            (recur (inc i)
                                   (conj! result
                                     (let [v (.getObject rs i)]
                                       (when v (str v)))))
                            (persistent! result)))
                        (thisfn))))))})
        (catch Exception e
          (log/error (str "Query failed: " sql " - " (.getMessage e)))
          (throw e)))))

  (close! [this]
    (try (.close conn) (catch Exception _))))

(defn create-source
  [uri-map _table-spec]
  (let [conn (connection uri-map)]
    (->PGSQLSource conn (:raw uri-map))))
