--- Dockerfile	2019-06-05 15:49:03.000000000 -0700
+++ Dockerfile_new	2019-06-05 15:56:20.000000000 -0700
@@ -31,6 +31,7 @@
 FROM debian:stable-slim

   RUN apt-get update \
+      && mkdir -p /usr/share/man/man1 /usr/share/man/man7 \
       && apt-get install -y --no-install-recommends \
         curl \
         freetds-dev \
@@ -39,9 +40,14 @@
         libzip-dev \
         make \
         sbcl \
+        postgresql-client \
+        inotify-tools \
         unzip \
       && rm -rf /var/lib/apt/lists/*

   COPY --from=builder /opt/src/pgloader/build/bin/pgloader /usr/local/bin
+
+  COPY ./docker-entrypoint.sh /
+  CMD ["/docker-entrypoint.sh"]

   LABEL maintainer="Dimitri Fontaine <dim@tapoueh.org>"
