#!/bin/sh

set -ex

trap "service mysql stop" 0 2 3 15
service mysql start

cd test
pg_virtualenv -i '--auth=trust' << EOF
	set -ex
	make -j1 local PGLOADER=/usr/bin/pgloader PGUSER=postgres DBPATH=sqlite/sqlite.db
EOF
